### ISSUE TITLE
Not working on Mac OS 14 Sonoma Beta Preview

### ISSUE THREAD

**Issue by NikarashiHatsu** [9tin9tin9/Mac-trackpad-mapper#9]
I tested it on Mac OS 14 Sonoma 23A5257q and it simply won't work as it was tried on Ventura.

**Comment by lokxii** [comment]
I am still using Monterey so I have no chance testing on Ventura...
Can you tell me what "won't work" means? Is it not compiling, or compiles fine but not working as expected (and what is the behavior you experience)? Then I can make some guesses and do research.

**Comment by NikarashiHatsu** [comment]
It successfully compiles, but the app not "capturing" the absolute trackpad position.

Edit to clarify: Even though I started the Absolute Tracking, my trackpad still behaves like as the normal trackpad.

**Comment by 9tin9tin9** [comment]
and does it work on Ventura?

**Comment by NikarashiHatsu** [comment]
It does work on Ventura

**Comment by lokxii** [comment]
This is how Trackpd Mapper works:
- UI written in Swift
- when "start absolute mapping" is clicked, the UI spawns the trackpad mapping utility process
- the utility process tries to obtain the trackpad device
- trackpad event handling callback is hooked to Multitouch event loop
- callback receives current finger position, calculates position of cursor on screen
- Post mouse moved event to Carbon event tap
- Cursor is teleported to the location you expected

There are multiple places that the utility may fail.
- Multitouch framework does not exist on Sonoma (apparently it exists because the program compiles fine)
- utility process cannot be spawned
- trackpad device cannot be obtained
- callback cannot be hooked to event loop
- Carbon mouse moved event cannot be posted to Carbon event tap

In fact I didn't add checks for failure in most of the places and logging in Trackpad Mapper so I can't tell which of the above fails. I will need to add logging first.

**Comment by Rexel26** [comment]
I'm on Sonoma beta 23A5312d on apple silicon and it works perfectly, so it might have been fixed at some point after a new beta release.

**Comment by lokxii** [comment]
Thank you! I don't have apple silicon nor using Sonoma beta so I can't really test it.
